ships/urls.py
from django.conf.urls import url
import views
 
urlpatterns = [
    url(r'all/$', views.ships_all, name='shipsall'),
    url(r'(?P<ship_pk>\d+)/detail/$', views.ship_detail, name='shipdetail'),
]

mining/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import uuid
from django.db import models
from django.conf import settings
from paypal.standard.forms import PayPalPaymentsForm

class Upgrade(models.Model):
	# Readable Info
	name = models.CharField(max_length=50)
	price = models.IntegerField()	
	production_increase = models.IntegerField()
	random_find_chance = models.IntegerField()
	random_find_increase = models.IntegerField()
	desc = models.TextField(max_length=500)
	image = models.ImageField(upload_to='images', blank=True, null=True)

	def __unicode__(self):
		return self.name

# Create your models here.
LVL_1 = 'ME'
LVL_2 = 'MD'
LVL_3 = 'MI'
LEVEL_CHOICE = (
	(LVL_1, 'Matter Extractor'),
	(LVL_2, 'Matter Devourer'),
	(LVL_3, 'Matter Inhaler'),
)
class Mine(models.Model):
	# Readable Info
	mine_size = models.CharField(max_length=50)	
	price = models.IntegerField()
	real_price=models.IntegerField(default=0)
	# how much is mined, and the modifier for the mine size
	production = models.IntegerField()
	mine_size_mod = models.IntegerField()
	# Upgrade Level
	level = models.CharField(max_length=50, choices=LEVEL_CHOICE, default=LVL_1)
	image = models.ImageField(upload_to='images', blank=True, null=True)

	@property
	def paypal_form(self):
	    paypal_dict = {
	        "business": settings.PAYPAL_RECEIVER_EMAIL,
	        "amount": self.level,
	        "currency": "USD",
	        "item_name": self.mine_size,
	        "invoice": "%s-%s" % (self.pk, uuid.uuid4()),
	        "notify_url": settings.PAYPAL_NOTIFY_URL,
	        "return_url": "%s/paypal-return" % settings.SITE_URL,
	        "cancel_return": "%s/paypal-cancel" % settings.SITE_URL
	    }

	    return PayPalPaymentsForm(initial=paypal_dict)	

	def __unicode__(self):
		return self.mine_size

home/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from ships.models import Spaceship
from mining.models import Mine
from planets.models import PlanetType
import random 

# Create your views here.
def home_view(request):
    return render(request, 'index.html')

def about_view(request):
	ships = Spaceship.objects.all()
	ship = random.choice(ships)
	mines = Mine.objects.all()
	mine = random.choice(mines)
	return render(request, 'about.html', {'ship': ship, 'mine': mine,})

home/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="colwrapper color">
    <h2 class="medheadline">Welcome</h2>
    <p>This is the galactic marketplace, where you can buy and trade raw elements, and start your own mining operations to provide long term profits. The Galaxy needs your materials, go deliver them!</p>
    <h2 class="medheadline">How it works</h2>
    <p>You gather elements by mining and trading with other companies. Then find planets with the best price to sell to!</p>
    <p>The more you sell to a planet the less they will pay until they put out new orders for materials, you'll have no idea when this will be however so take advantage of good prices while they are there. Just remember finding the best price takes time, letting other players buy from you can leave you with more time to decide what ship your going to purchase next!</p>
    <div class="shipoverlay">
        <h1>{{ ship.ship }}</h1>           
        <img src="/media/{{ ship.image }}" class="ship">
        <div class="shipinfo">
            <h2>Faster ships will let you move resources more quickly!</h2> 
        </div>
    </div>
    <hr>
    <h2 class="medheadline">Anything has a price</h2>
    <p>You can't stop other players buying from your stores, Emporer Zog demands that money and materials always keep moving. However, if your mining more Zorkium than anyone else, there's nothing to stop you charging what you want to other players to price them out of any profits. They will have to find them elsewhere.</p>
    <div class="shipoverlay">
        <h1>{{ mine.get_level_display }}</h1>           
        <img src="/media/{{ mine.image }}" class="ship">
        <div class="shipinfo">
            <h2>Mines will continually produce resources for you.</h2> 
        </div>
    </div>
    <hr>
    <h2 class="medheadline">Lets get started!</h2>
    <p>Just click the registration and choose a company name on the next page! You'll be given some things to get you started! Happy Trading!</p>
    <hr>
    <button type="submit" class="btn CCbutton" onclick="location.href='/company/profile'">Register</button> 
    <hr>
</div>

{% endblock %}

home/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="bigheadline">
	WELCOME TRADER
</div>
<div class="homewrapper">
<!-- 	<img src="{% static 'images/a.jpg' %}"> -->
	{% if user.is_active %}
	<div class="home">
		<p>Start your own Intergalactic Trading Company.</p>
		<button type="submit" class="btn CCbutton" onclick="location.href='/company/profile'">Company Page</button>	
	</div>	
	{% else %}
	<div class="home">
		<p>Start your own Intergalactic Trading Company.</p>
		<button type="submit" class="btn CCbutton" onclick="location.href='/register'">Register</button	
	</div>
	{% endif %}
</div>

{% endblock %}