companies/urls.py
from django.conf.urls import url, include
import views
urlpatterns = [
	# all companies url
	url(r'all/$', views.all_companies, name='allcompanies'),
    # company detail
    url(r'detail/(?P<company_pk>\d+)/$', views.company_detail, name='companydetail'),
	# create company urls
    url(r'new/$', views.new_company, name='newcompany'),
    url(r'profile/$', views.company_profile, name='company'),
    url(r'edit/$', views.edit_company, name='editcompany'),
    url(r'trades/$', views.trade_list, name='tradelist'),
    # change company pricing url
    url(r'(?P<element_id>\d+)/$', views.element_price, name='elementprice'),
    # set-up trade url
    url(r'company/(?P<seller_pk>\d+)/(?P<storage_pk>\d+)/trade/$', views.company_trade, name='companytrade'),
    url(r'planet/(?P<buyer_pk>\d+)/(?P<storage_pk>\d+)/trade/$', views.planet_trade, name='planettrade'),    
    # Ship Urls
    url(r'^ships/', include('ships.urls')),
    # Ship Urls
    url(r'^mines/', include('mining.urls')),
]

ships/urls.py
from django.conf.urls import url
import views
 
urlpatterns = [
    url(r'all/$', views.ships_all, name='shipsall'),
    url(r'(?P<ship_pk>\d+)/detail/$', views.ship_detail, name='shipdetail'),
]

companies/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.forms import ModelForm
from datetime import datetime, timedelta
import random, math
from accounts.models import User
from elements.models import Element
from ships.models import Spaceship
from mining.models import Mine, Upgrade
from planets.models import Planet


# Planet types for selection
CONTINENTAL = 'CN'
TROPICAL = 'TR'
OCEANIC = 'OC'
DESERT = 'DS'
TUNDRA = 'TN'
PLANET_CHOICE = (
	(CONTINENTAL, 'Continental'),
	(TROPICAL, 'Tropical'),
	(OCEANIC, 'Oceanic'),
	(DESERT, 'Desert'),
	(TUNDRA, 'Tundra'),
)

# Create your models here.
class Company(models.Model):
	
	user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
	locationx = models.IntegerField(default=0)
	locationy = models.IntegerField(default=0)
	locationz = models.IntegerField(default=5000)
	money = models.IntegerField(default=10000)
	name = models.CharField(max_length=50, unique=True)
	description = models.TextField(max_length=500)
	image = models.ImageField(upload_to='images', blank=True, null=True)
	planets = models.CharField(max_length=2, choices=PLANET_CHOICE, default=CONTINENTAL)
	last_checked = models.DateTimeField(auto_now_add=True, blank=True)

	def __unicode__(self):
		return self.name


class StorageManager(models.Manager):
	def give_company_elements(self, company_id, element_id):
		"""Get User/Company object and assign Element to it."""
		company_element = self.create(
			company=company_id,
			element=element_id,
			price= random.randint(50, 200),
			amount=random.randint(1, 50),
		)
		company_element.save()			
		return company_element	

class CompanyStorage(models.Model):

	company = models.ForeignKey(Company, on_delete=models.CASCADE)
	element = models.ForeignKey(Element, on_delete=models.CASCADE)
	amount = models.IntegerField()
	price = models.IntegerField()

	objects = StorageManager()

	def __unicode__(self):
		return str(unicode(self.company) + ' - ' + unicode(self.element))


class ShipManager(models.Manager):

	def create_ship (self, ship, buyer):
		"""Create a ship and assign it to a User then return the object"""
		new_ship = self.create(
			owner=buyer,
			ship=ship,
			amount=0,
			in_use=0,
		)
		return new_ship

	def add_ship (self, amount, ship, buyer):
		"""Find current ship type and assign 1 more to a User then save the object"""
		owned_ship = Ownership.objects.filter(owner=buyer, ship=ship)[0]
		owned_ship.amount += amount
		buyer.money -= ship.price * amount
		buyer.save()
		owned_ship.save()	

class Ownership(models.Model):

	owner = models.ForeignKey(Company, on_delete=models.CASCADE)
	ship = models.ForeignKey(Spaceship, on_delete=models.CASCADE)
	amount = models.IntegerField()
	in_use = models.IntegerField()

	objects = ShipManager()

	def __unicode__(self):
		return self.owner.name + ' - ' + self.ship.ship

class MineManager(models.Manager):

	def mine_elements(self, company):
		"""Get Player Mines and return of list of any that produce Elements."""
		owned_mines = MineOwnership.objects.filter(owner=company)
		# get time difference between last time user is on profile screen
		time_multiplier = timezone.now() - company.last_checked 
		time_in_hours = time_multiplier.days * 24.0 + (time_multiplier.seconds / 3200.0)
		round(time_in_hours, 2) # rounds result in hours
		all_minerals = set()

		for owned in owned_mines: # iterate through all owned mines.
			mine = owned.mine # type of mine
			# target specific company storage of one element
			company_mineral = CompanyStorage.objects.filter(element=owned.element, company=company)[0]
			# add minerals based on time that has passed			
			mineral_added = (mine.production * mine.mine_size_mod * owned.amount) * time_in_hours
			mineral_added = round(mineral_added) # round to int as minerals only in ints
			if mineral_added > 0: # wait until enough time has passed for 1 to be created before resetting.	
				company_mineral.amount += mineral_added # add minerals to company
				company_mineral.save() # save result
				new_mineral = (mine.mine_size, owned.amount, company_mineral.element.name, mineral_added)			
				all_minerals.add(new_mineral)		 
				# prevent time resetting if no minerals were added (not enough time passed)
				company.last_checked = timezone.now()
				company.save()
		return all_minerals

	def create_mine (self, mine, element, buyer):
		"""Create a Mine and assign it to a User then return the object"""
		new_mine = self.create(
			owner=buyer,
			mine=mine,
			element=element,
			amount=0,
		)
		return new_mine

	def add_mine (self, amount, element, mine, buyer):
		"""Find current mine type and assign 1 more to a User then save the object"""
		owned_mine = MineOwnership.objects.filter(owner=buyer, element=element, mine=mine)[0]
		owned_mine.amount += amount
		buyer.money -= mine.price * amount
		buyer.save()
		owned_mine.save()

class MineOwnership(models.Model):
	owner = models.ForeignKey(Company, on_delete=models.CASCADE)
	mine = models.ForeignKey(Mine, on_delete=models.CASCADE)
	element = models.ForeignKey(Element, on_delete=models.CASCADE)
	amount = models.IntegerField()
	upgrade = models.ForeignKey(Upgrade, on_delete=models.CASCADE, blank=True, null=True)

	objects = MineManager()

	def __unicode__(self):
		return self.owner.name + ' - ' + self.mine.mine_size

class TradeManager(models.Manager):
	def company_trade(self, seller, company_element, amount, buyer, owned_ship):
		"""Get two Company objects and tranfer money and elements between them return trade Object."""
		owned_ship.in_use += 1
		owned_ship.save()
		buyer_storage = CompanyStorage.objects.filter(company=buyer, element=company_element.element)
		buyer_storage = buyer_storage[0]


		# locations/distance calculations for traders
		x = buyer.locationx
		x2 = seller.locationx
		y = buyer.locationy
		y2 = seller.locationy
		z = buyer.locationz
		z2 = seller.locationz
		distance = math.sqrt((x-x2)*(x-x2) + (y-y2)*(y-y2) + (z-z2)*(z-z2))
		# work out fuel cost from distance
		fuel_cost = distance / 300 * amount
		round(fuel_cost)
		price = amount * company_element.price + fuel_cost
		# make a new trade
		trade = self.create(
			buyer=buyer,
			seller=seller,
			element=company_element.element,
			amount=amount,
			price=price,
			distance=distance,
			status='Pending',
			ship=owned_ship,
		)
		# find out when trade will finish
		ship_speed_multiplier = distance / owned_ship.ship.speed
		now = trade.date_created
		trade_finish_date = trade.date_created + timedelta(seconds=ship_speed_multiplier)
		trade.date_to_finish = trade_finish_date
		trade.save()

		company_element.amount -= amount
		company_element.save()
		seller.money += price		
		seller.save()

		buyer.money -= price		
		buyer.save()					
		return trade

	def check_trade_status(self, company):
		"""Look at current User trades then modify and return any that have passed completion date"""
		company_trades = CompanyTrade.objects.filter(buyer=company, status='Pending')

		for trade in company_trades:
			company_element = CompanyStorage.objects.filter(element=trade.element, company=company)[0]
			if timezone.now() >= trade.date_to_finish:
					trade.ship.in_use -= 1
					if trade.ship.in_use < 0:
						trade.ship.in_use = 0
					trade.ship.save()
					company_element.amount += trade.amount
					company_element.save()
					trade.status = 'Completed'
					trade.save()

class CompanyTrade(models.Model):

	buyer = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='buyer_trade')
	seller = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='seller_trade')
	element = models.ForeignKey(Element, on_delete=models.CASCADE)
	amount = models.IntegerField()
	price = models.IntegerField()
	distance = models.IntegerField()
	date_created = models.DateTimeField(auto_now_add=True)
	date_to_finish = models.DateTimeField(auto_now_add=True)
	status = models.CharField(max_length=50)
	ship = models.ForeignKey(Ownership, on_delete=models.CASCADE)

	objects = TradeManager()

	def __unicode__(self):
		return self.buyer.name + ' - ' + self.seller.name

class PlanetTradeManager(models.Manager):
	def planet_trade(self, seller, planet_element, amount, buyer, owned_ship):
		"""Get a Planet and Company object and tranfer money and elements between them return trade Object."""
		owned_ship.in_use += 1
		owned_ship.save()
		seller_storage = CompanyStorage.objects.filter(company=seller, element=planet_element.element)
		seller_storage = seller_storage[0]

		# locations/distance calculations for traders
		x = buyer.locationx
		x2 = seller.locationx
		y = buyer.locationy
		y2 = seller.locationy
		z = buyer.locationz
		z2 = seller.locationz
		distance = math.sqrt((x-x2)*(x-x2) + (y-y2)*(y-y2) + (z-z2)*(z-z2))
		# work out fuel cost from distance
		fuel_cost = distance / 300 * amount
		round(fuel_cost)
		price = amount * planet_element.price - fuel_cost
		# make a new trade
		trade = self.create(
			buyer=buyer,
			seller=seller,
			element=planet_element.element,
			amount=amount,
			price=price,
			distance=distance,
			status='Pending',
			ship=owned_ship,
		)
		# find out when trade will finish
		ship_speed_multiplier = distance / owned_ship.ship.speed
		now = trade.date_created
		trade_finish_date = trade.date_created + timedelta(seconds=ship_speed_multiplier)
		trade.date_to_finish = trade_finish_date
		trade.save()

		planet_element.price -= round(amount / random.randint(9, 18))
		planet_element.save()
		seller.money += price		
		seller.save()
		seller_storage.amount -= amount
		seller_storage.save()				
		return trade

	def check_planet_trade_status(self, company):
		"""Look at current User trades then modify and return any that have passed completion date"""
		planet_trades = PlanetTrade.objects.filter(seller=company, status='Pending')

		for trade in planet_trades:
			if timezone.now() >= trade.date_to_finish:
					trade.ship.in_use -= 1

companies/forms.py
from django import forms
from django.forms import ModelForm
from .models import Company, CompanyStorage, CompanyTrade, Ownership, PlanetTrade
 
class CompanyForm(forms.ModelForm):
 
    class Meta:
        model = Company
        fields = ('name', 'description', 'image', 'planets')

class EditForm(forms.ModelForm):
 
    class Meta:
        model = Company
        fields = ('name', 'description', 'image')

class PriceForm(forms.ModelForm):
 
    class Meta:
        model = CompanyStorage
        fields = ('price',)

class TradeForm(forms.ModelForm):

    class Meta:
        model = CompanyTrade
        fields = ('amount', 'ship')
    # Custom Form allows player to choose which ship they want to transport their trade.

    # set init to take user variable that lets me target logged in user for ship field.
    def __init__(self, user, *args, **kwargs):
        super(TradeForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['ship'].queryset = Ownership.objects.filter(owner=user)

class PlanetTradeForm(forms.ModelForm):

    class Meta:
        model = PlanetTrade
        fields = ('amount', 'ship')
    # Custom Form allows player to choose which ship they want to transport their trade.

    # set init to take user variable that lets me target logged in user for ship field.
    def __init__(self, user, *args, **kwargs):
        super(PlanetTradeForm, self).__init__(*args, **kwargs)
        if user:
            self.fields['ship'].queryset = Ownership.objects.filter(owner=user)

companies/templates/companiespage.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load companies_extras %}
<h1 class="bigheadline">TRADER INFO</h1>
<hr>
{% for company in companies %}
    <div class="color"> 
        <div class="rowcolwrapper profilewrapper">	
        	<div class="colwrapper">	
        		<h2 >Trader:</h2>	
        		<p>{{ company.name }}</p>
        		<h2>Glorkian Credits: </h2>
        		<p>{% readable_int company.money %}c</p>
                <h2>Planet Type: </h2>
                <p>{{ company.get_planets_display }}</p>
                <h2>Location: </h2>
                <p>{{ company.locationx }}, {{ company.locationy }}, {{company.locationz}}</p>
                <h2>Distance: </h2>
                <p>{% find_distance company.locationx company.locationy company.locationz player.locationx player.locationy player.locationz %}</p>
                <button class="btn CCbutton" onclick="location.href='{% url 'companydetail' company.pk %}'">More</button>
        	</div>
        	<div class="colwrapper">
                    {% if company.image %}
                            <img src="/media/{{ company.image }}" class="profileimg">
                    {% else %}
                            <img src="{% static 'images/mining_facility.jpg' %}" class="profileimg">       
                    {% endif %}         
                <h2>Description: </h2>
                <p class="profiledesc">{{ company.description }}</p>
        	</div>
        </div>
    </div>
<hr>
{% endfor %}
{% endblock %}

companies/templates/companydetail.html
{% extends "base.html" %}
{% block content %}
{% load static %}
{% load companies_extras %}
<h1 class="bigheadline">TRADER INFO</h1>
<hr>
<div class="color"> 
    <div class="rowcolwrapper profilewrapper">	
    	<div class="colwrapper">	
    		<h2 >Trader:</h2>	
    		<p>{{ company.name }}</p>
    		<h2>Glorkian Credits: </h2>
    		<p>{% readable_int company.money %}c</p>
            <h2>Planet Type: </h2>
            <p>{{ company.get_planets_display }}</p>
            <h2>Location: </h2>
            <p>{{ company.locationx }}, {{ company.locationy }}, {{company.locationz}}</p>
            <h2>Distance: </h2>
            <p>{% find_distance company.locationx company.locationy company.locationz player.locationx player.locationy player.locationz %}</p>
    	</div>
    	<div class="colwrapper">
                {% if company.image %}
                        <img src="/media/{{ company.image }}" class="profileimg">
                {% else %}
                        <img src="{% static 'images/mining_facility.jpg' %}" class="profileimg">       
                {% endif %}         
            <h2>Description: </h2>
            <p class="profiledesc">{{ company.description }}</p>
    	</div>
    </div>
</div>
<hr>

<div class=" rowwrapper">
{% for companyelement in companyelements %}
<div class="rowcolwrapper elementwrapper rel color">
        <div class="el borderbottom" style="background-color: rgb({{ companyelement.element.color }});">
            <div>
                <h1> {{ companyelement.element.tag }} </h1>
            </div>
            <p> {{ companyelement.amount}} Mt's</p>
        </div>     
        <div class="colwrapper borderbottom" style="background-color: rgba({{companyelement.element.color}},0.2);">
            <div class="elementinfo borderbottom">   
                <p>Trader:</p>
                <p>{{ companyelement.company }}</p>
            </div>
            <div class="elementinfo borderbottom">   
                <p>Element:</p>
                <p>{{ companyelement.element.name }}</p>
            </div>
            <div class="elementinfo borderbottom">               
                <p>Weight:</p>
                <p>{{ companyelement.element.weight }}u</p>
            </div>         
            <div class="elementinfo borderbottom"> 
                <p>Price:</p>
                <p>{{ companyelement.price }} Glorks</p>               
            </div>
            <div class="elementinfo borderbottom"> 
                <p>Amount:</p>
                <p>{{ companyelement.amount }} Mt's</p>               
            </div>
            <div class="elementinfo"> 
                <p>Sell Stock:</p>
                <button class="btn CCbutton" onclick="location.href='{% url 'companytrade' companyelement.company.pk companyelement.pk %}'">Buy</button>
            </div>
        </div>

</div>          
{% endfor %}
</div>
{% endblock %}

companies/templates/companytrade.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load companies_extras %}
{% block content %}
    <span id="tradepage"></span>
    <div class="colwrapper color">  
            <div class="colwrapper" style="background-color: rgba({{companyelement.element.color}},0.2);">
                <div class="elementinfo borderbottom">     
                    <p>Trader:</p>
                    <p>{{ companyelement.company.name }}</p>
                </div>
                <div class="elementinfo borderbottom">     
                    <p>Element:</p>
                    <p>{{ companyelement.element.name }}</p>
                </div>       
                <div class="elementinfo borderbottom"> 
                    <p>Seller Amount:</p>
                    <p>{{ companyelement.amount }} Mt's</p>               
                </div>
                <div class="elementinfo borderbottom"> 
                    <p>Your Amount:</p>
                    <p>{{ playerelement.amount }} Mt's</p>               
                </div>
                <div class="elementinfo borderbottom"> 
                    <p>Price:</p>
                    <p ><span id="pricecheck">{{ companyelement.price }}</span> Glorks</p>               
                </div>                           
                <div class="elementinfo borderbottom">     
                        <p>Average Sell Price:</p>
                        <p>{{ company_average }} Glorks</p>
                </div>
                <div class="elementinfo borderbottom">     
                        <p>Average Planet Buy Price:</p>
                        <p>{{ planet_average }} Glorks</p>
                </div>  
                <div class="elementinfo borderbottom">
                    <!-- find company distance function is inside companies_extras.py-->
                    {% find_distance companyelement.company.locationx companyelement.company.locationy companyelement.company.locationz player.locationx player.locationy player.locationz as the_distance %}
                    <p>Distance:</p>
                    <p> <span id="distance">{{ the_distance }}</span>: LY</p>
                </div>
            </div>                     
        <h3>How many do you want to buy?</h3>
        <h3 class="medheadline">Your Money:</h3>
        <h3 class="bottomborder">{% readable_int playerelement.company.money %} Glorks</h3>
        <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | as_bootstrap}}                
                <button type="submit" class="btn CCbutton">Buy for <span id="totalprice">0</span> Glorks</button>
                <span>+ Shipping: <span id="fuelcost"></span> g</span>
                <hr>
                {% if messages %}
                    <div class="alert alert-success">
                        <div class="messages">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
        </form>
    </div>

{% endblock %}

companies/templates/editprofile.html
{% extends "base.html" %}
{% block content %}
        {% load bootstrap_tags %}
        <div class="colwrapper color">
        <p>You are logged in as {{ user.email }} and your last login was {{ user.last_login }}</p>
        
        <h1>Choose your Company Details!</h1>
        <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | as_bootstrap}}
                <button type="submit" class="btn CCbutton">Save</button>
        </form>
        </div>
{% endblock %}

companies/templates/elementprice.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% block content %}
    <!-- PLAYER CHOOSE NEW PRICE FOR OWN ELEMENT PAGE -->
    <div class="colwrapper color">	
            <div class="colwrapper borderbottom" style="background-color: rgba({{companyelement.element.color}},0.2);">
                <div class="elementinfo borderbottom">     
                        <p>Element:</p>
                        <p>{{ companyelement.element.name }}</p>
                    </div>
                    <div class="elementinfo borderbottom">               
                        <p>Weight:</p>
                        <p>{{ companyelement.element.weight }}u</p>
                    </div>         
                    <div class="elementinfo borderbottom"> 
                        <p>Price:</p>
                        <p>{{ companyelement.price }} Glorks</p>               
                    </div>
                    <div class="elementinfo borderbottom"> 
                        <p>Your Amount:</p>
                        <p>{{ companyelement.amount }} Mt's</p>               
                    </div>
            </div>
            <div class="colwrapper borderbottom" style="background-color: rgba({{companyelement.element.color}},0.2);">
                <div class="elementinfo borderbottom">     
                        <p>Average Company Price:</p>
                        <p>{{ average }} Glorks</p>
                    </div>        
            </div>

        <h1>Choose your new price, be competitive!</h1>
        <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | as_bootstrap}}
                <button type="submit" class="btn CCbutton" >Save</button>
        </form> 
    </div>                
{% endblock %}

companies/templates/planettrade.html
{% extends "base.html" %}
{% load bootstrap_tags %}
{% load companies_extras %}
{% block content %}
    <!-- PAGE FOR PLAYER TRADING WITH PLANET -->
    <span id="tradepage"></span>
    <div class="colwrapper color">  
            <div class="colwrapper" style="background-color: rgba({{planetelement.element.color}},0.2);">
                <div class="elementinfo borderbottom">     
                        <p>Planet:</p>
                        <p>{{ planetelement.planet.name }}</p>
                </div>
                <div class="elementinfo borderbottom">     
                        <p>Element:</p>
                        <p>{{ planetelement.element.name }}</p>
                </div>
                <div class="elementinfo borderbottom">               
                    <p>Weight:</p>
                    <p>{{ planetelement.element.weight }}u</p>
                </div>         
                <div class="elementinfo borderbottom"> 
                    <p>Price:</p>
                    <p ><span id="pricecheck">{{ planetelement.price }}</span> Glorks</p>               
                </div>
                <div class="elementinfo borderbottom">     
                        <p>Average Company Sell Price:</p>
                        <p>{{ company_average }} Glorks</p>
                </div>
                <div class="elementinfo borderbottom">     
                        <p>Average Planet Buy Price:</p>
                        <p>{{ planet_average }} Glorks</p>
                </div> 
                <div class="elementinfo borderbottom">
                        <!-- find company distance     -->
                        {% find_distance planetelement.planet.locationx planetelement.planet.locationy planetelement.planet.locationz player.locationx player.locationy player.locationz as the_distance %}
                        <p>Distance:</p>
                        <p> <span id="distance">{{ the_distance }}</span>: LY</p>
                </div> 
                <div class="elementinfo borderbottom">     
                        <p>Your Amount:</p>
                        <p>{{ playerelement.amount }} Mt's</p>
                </div>        
            </div>           
        <h3>How many do you want to sell?</h3>
        <h3 class="smallheadline">Your Amount:</h3>
        <h3 class="bottomborder">{{ playerelement.amount }} Mt's Glorks</h3>
        <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form | as_bootstrap}}                
                <button type="submit" class="btn CCbutton">Sell for <span id="totalprice">0</span> Glorks</button>
                <span>- Shipping: <span id="fuelcost"></span> g</span>
                <hr>
                {% if messages %}
                    <div class="alert alert-success">
                        <div class="messages">
                            {% for message in messages %}
                                {{ message }}
                            {% endfor %}
                        </div>
                    </div>
                {% endif %}
        </form>
    </div>

{% endblock %}

companies/templates/profileform.html
{% extends "base.html" %}
{% block content %}
        {% load bootstrap_tags %}
        <div class="colwrapper color">
                <p>You are logged in as {{ user.email }} and your last login was {{ user.last_login }}</p>
                
                <h2>Now Choose your Company Details!</h2>
                <p>Once you have created your company details, you will be given your first ship and a small mine to get you started.</p>
                <form method="POST" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form | as_bootstrap}}
                        <button type="submit" class="btn CCbutton">Save</button>
                </form>
        </div>
{% endblock %}

companies/templates/tradelist.html
{% extends "base.html" %}
{% block content %}
<h2 class="medheadline">
   RECENT TRADES
</h2>
<hr>
<div class="colwrapper">       
    {% for trade in trades %}
        <div class="color">
            <div class="tradewrapper borderbottom"  style="background-color: rgba({{trade.element.color}},0.2);">
                <div class="trade">   
                    <h3>Element:</h3>
                    <p>{{ trade.element.name }}</p>
                </div>
                <div class="trade">               
                    <h3>Buyer:</h3>
                    <p>{{ trade.buyer.name }}</p>
                </div>         
                <div class="trade"> 
                    <h3>Merchant:</h3>
                    <p>{{ trade.seller.name }}</p>               
                </div>
                <div class="trade"> 
                    <h3>Amount:</h3>
                    <p>{{ trade.amount }} Mt's</p>               
                </div>
                <div class="trade"> 
                    <h3>Price Paid:</h3>
                    <p>{{ trade.price }}c</p>               
                </div>
                <div class="trade"> 
                    <h3>Finish Date:</h3>
                    <p>{{ trade.date_to_finish }}</p>               
                </div>
                <div class="trade"> 
                    <h3>Status:</h3>
                    <p>{{ trade.status }}</p>               
                </div>
            </div> 
        </div>          
    {% endfor %}
</div>
{% endblock %}